### ISSUE TITLE
Choosing different shifts

### ISSUE THREAD

**Issue by LourencoPonces** [joaocmd/Criador-Horarios#6]
One useful feature would be the possibility of choosing to be in both Alameda and Tagus shifts for the theoretical classes of the same course. For example, if a given course has 2 theoretical classes with 2 pairs of shifts, 1 pair in Alameda and the other pair in Tagus, it would be nice to choose one shift from one pair (Alameda) and choose the other shift from the other pair (Tagus).

**Comment by joaocmd** [comment]
We don't really think it makes sense to allow for selecting lessons individually, even though we understand the reason why you might want to do so. What we might try to add is the ability to select two shifts without replacing by pressing shift+event or something. This would be different than your request because all 4 lessons would appear on the schedule, but I think it's the best we can do considering the domain.
